### ISSUE TITLE
Things aren't resolving...

### ISSUE THREAD

**Issue by haydennyyy** [haydennyyy/polaris#1]
For some reason, when trying to run `com.haydennyyy.polaris.Bot.main`, it gives me a *ton* of `x cannot be resolved to a type` errors.

## 📄 Logs
```
Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The import com.haydennyyy.polaris.core.Command cannot be resolved
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	The constructor CommandRegistry(Map<String,Command>) refers to the missing type Command
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	Command cannot be resolved to a type
	The method run(GuildMessageReceivedEvent) of type CommandRegistry.NotFoundCommand must override or implement a supertype method

	at com.haydennyyy.polaris.core.CommandRegistry.<init>(CommandRegistry.java:3)
	at com.haydennyyy.polaris.Bot.<clinit>(Bot.java:23)
```

**Comment by haydennyyy** [comment]
Turns out it was an issue with VS Code, had to clean my Java Workspace Folder (part of the RedHat Java extension)
